spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_auth_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.postgresql.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration